name: Deploy
on:
  push:
    branches:
      - develop
jobs:
  build:
    name: Build and push docker image to registry
    strategy:
      matrix:
        arch: [ amd64, arm64 ]
        include: 
          - arch: amd64
            runner: ubuntu-latest
            platform: linux/amd64
          - arch: arm64
            runner: ubuntu-24.04-arm
            platform: linux/arm64
    runs-on: ${{ matrix.runner }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Shallow clones should be disabled for a better relevancy of analysis
      - name: Login to GHCR 
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          platforms: ${{ matrix.platform }}
          tags: |
            ghcr.io/ponche/hopper:dev-latest
            ghcr.io/ponche/hopper:dev-v${{ github.run_number }}


  update:
    name: Update the VPS with Ansible
    runs-on: ubuntu-latest
    needs: build
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: add the private key 
      run: echo "${{ secrets.VPS_KEY }}" > private-key

    - name: change authorisation on the file private-key
      run: chmod 700 private-key

    - name: Create inventory ansible
      run:  echo "${{ secrets.INVENTORY }}" > inventory.ini

    - name: download the collection community.docker on Galaxy
      run: ansible-galaxy collection install community.docker

    - name: launch the playbook update VPS 
      run: ansible-playbook --key-file private-key -i inventory.ini ansible/updateSiteKapoot.yml
